# Generated by Django 6.0.1 on 2026-02-24 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=200, null=True)),
                ('personality', models.CharField(blank=True, max_length=20, null=True)),
                ('favorite_artists', models.ManyToManyField(blank=True, related_name='favorite_artists', to='music.artist')),
                ('played_songs', models.ManyToManyField(blank=True, related_name='played_songs', to='music.song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
