# Generated by Django 4.2.29 on 2026-03-22 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_alter_song_audio_file_alter_song_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('current_song_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_playing', models.BooleanField(default=False)),
                ('timestamp', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
