# Generated by Django 4.2.29 on 2026-04-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_likedsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
