# Generated by Django 4.2.29 on 2026-04-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_song_album_song_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='followed_artists',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='music.artist'),
        ),
    ]
