# Generated by Django 4.2.29 on 2026-04-27 02:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0010_userprofile_followed_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collaborative_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='invite_token',
            field=models.CharField(blank=True, max_length=65, null=True, unique=True),
        ),
    ]
